WIDTH = 1024
HEIGHT = 720
FPS = 60

PLAYER_SPEED = 220
NPC_SPEED = 100  

SPRITE_DIR = "assets/caramel"
NPC_DIR = "assets/dobermann"

FRAME_SIZE = 48

BORDER_THICKNESS = 10
TOP_BORDER_THICKNESS = BORDER_THICKNESS + 30

SCALE_FACTOR = 2.0
NPC_SCALE = 2.0   
